import ReduxProvider from '@/Context/reduxContext/ReduxProvider';
import './globals.css'
import { Work_Sans } from 'next/font/google';
import Navbar from '@/Components/Shared/Navbar/Navbar';
import SidebarMenu from '@/Components/Shared/Sidebar/SidebarMenu';
import Modal from '@/Components/Modal/Modal';

const inter = Work_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <main>
          <ReduxProvider>
            <Navbar />
            <Modal/>
            <div className='flex'>
              <div className='w-[15%]'>
              <SidebarMenu/>
              </div>
              <div className='w-full'>
                <div className='mt-16 lg:w-6/5 w-11/12 mx-auto'>
                  {children}
                </div>
              </div>
            </div>
          </ReduxProvider>
        </main>
      </body>
    </html>
  )
}
